### ISSUE TITLE
🐛 [BUG] - fish , locals, firefox, hyprland, keybinds

### ISSUE THREAD

**Issue by Ayanashi** [Matt-FTW/dotfiles#15]
### Did you check existing issues?

- [X] I have searched the existing issues of the repo
- [X] I have searched the existing issues of used programs related to this issue

### Description of the bug

```bash
so much issues, copyin and paste folders broke permissions for username (matt) 
your dotfiles are pretty nice but repeat so much issues but let's start for beginning
1. fish (the big and problematic isssue)

"fish: Unknown command: vivid
~/.config/fish/user_variables.fish (line 1): 
vivid generate catppuccin-macchiato
^~~~^
in command substitution
	called on line 88 of file ~/.config/fish/user_variables.fish
from sourcing file ~/.config/fish/user_variables.fish
	called on line 1 of file ~/.config/fish/config.fish
from sourcing file ~/.config/fish/config.fish
	called during startup
~/.config/fish/user_variables.fish (line 88): Unknown command
set -xg LS_COLORS (vivid generate catppuccin-macchiato)
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
from sourcing file ~/.config/fish/user_variables.fish
	called on line 1 of file ~/.config/fish/config.fish
from sourcing file ~/.config/fish/config.fish
	called during startup"
first error about vivid and user_variables
 
2. FISH user permissions
"failed to create directory '/home/matt/.cache/yay': mkdir /home/matt: permission denied"
with this error instead cannot use yay for install or update system

3. Hyprland
"config error /home/user/.config/hyrp/plugins/hyprexopo.conf at line 18: invalid dispatcher, requested 'hyprexpo:expo' " does not exist

"config error in file /home/user/.config/plugins/hyprsplit.conf at line 9: invalid dispatcher resquest 'split:workspace; does not exit
some for line 10,11 and i get more 111 lines errors"
4. Hyprland binds
i notice you using us,es input and is okey i can change it but in bind some binding not exist with my keyboard i change the dmenu launcher with other bins same for rofi-scripts, for expample (bind = $mainMod, 61, exec, $rofi-scripts/keybindings/keybindings # /) the 61 bind for key is stand for? i got a 60% keyboard so i don't have idea how launch some apps

5. firefox
after copy .config/firefox
i can't opening for permissions
```

### Reproduction steps

```bash
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. And so on...
```

### Expected Behavior

i can say your config is very good but is working only for you if someone copy and paste your config and .local folder can broke him system, before put online ur dotfiles u need to check if is working for everyone or warn the people in ur readme.md can cause some issues, if you copy ur dotfiles in vm with new user u can see so much erros for you dotfiles, thanks for sharing ur dotfiles are pretty awesome but need some fix 

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Environment

```bash
Linux Distro, Linux Version, Hyprland Version...
OS ➜ Arch Linux x86_66                                                      
Kernel ➜ Linux 6.10.3-arch1-2
Shell ➜ fish 3.7.1
WM ➜ Hyprland (Wayland)
Terminal ➜ kitty 0.35.2
```

**Comment by Matt-FTW** [comment]
Hey!

Everything is fixed already in upstream. To give you some information about the issues:

1. **Fish**: The issue was related to not checking if vivid was installed, as well as adding it to the packages to install in the installation section of the README. With 5da813a and cd639ab, the issue is resolved.
About the reference to my home dir, it was a mistake in my part for uploading the fish_variables file from the fish config directory. Resolved in 6482fa2.

2. **Permissions**: Here I was using an absolute path instead of a relative on the yay config file. They were deleted on this commit: 2f039c7 

3. **Hyprland Plugins**: I had some plugins enabled by default in my system but I didnt specified them on the installation instructions, so I decided just to comment the lines importing and enabling them.If you want to enable those plugins, you can check the plugins official documentation on how to install them.

4. I didnt understand exactly what you said over here. From what I get, you're trying to change some bindings right? Then assign the key code or the key value? If you're trying to know what the code I have on some, on the right there is a comment where you have the value it represents. The one you brought up as an example has at the right a comment starting with the # sign and then an **/**.  It means that that keycode is equal to the slash. If you want to know the keycodes for yourself, you can try [wev](https://github.com/jwrdegoede/wev). It's basically xev for Wayland.

5. There is no ~/.config/firefox directory uploaded in here. If you are referring to the ~/.config/browser folder, i checked the permissions and there isnt any issue about them. 
 
I'll put a message before the installation instructions to inform it is under construction.

Thanks for your help!
Be sure to let me know if you find any other issues or there's something I forgot :)

**Comment by Ayanashi** [comment]
Thank you very much, sorry for my late response i will check it again and tell you! ( repeat this dotfiles are very cool!)

**Comment by Ayanashi** [comment]
all good with minor issues, (found some issue with mise-poetry but no problem with all) thanks mate!

**Comment by Matt-FTW** [comment]
> all good with minor issues, (found some issue with mise-poetry but no problem with all) thanks mate!

Removed poetry on this commit (44844e0), it should now be fixed :)
