### ISSUE TITLE
🐛 Bug: Can't start waybar

### ISSUE THREAD

**Issue by nvn-bisht** [Matt-FTW/dotfiles#24]
### Did you check existing issues?

- [X] I have searched the existing issues of the repo
- [X] I have searched the existing issues of used programs related to this issue
- [X] I have read the [FAQ](https://github.com/Matt-FTW/dotfiles/blob/main/.github/FAQ.md)

### Description of the bug

Unable to receive desktop appearance: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop

### Screenshots

![captura-2024-10-02-1727884263](https://github.com/user-attachments/assets/da736539-5bbd-4bd3-be61-3cdc015b9cbb)

### Environment

Arch Linux, Linux 6.11.1-arch1-1

**Comment by Matt-FTW** [comment]
Hey!,

Thats not an issue, the log line is just for info. You have to change the output code for the bar you want to use. Check it out [over here](https://github.com/Matt-FTW/dotfiles/blob/87afd76a867e3f933c418d3c826d3308c95dc7fc/.config/waybar/config.jsonc#L6).

Next time, check the [post-installation instructions](https://github.com/Matt-FTW/dotfiles#heavy_plus_sign-post-installation). This issue is already covered over there.
