### ISSUE TITLE
📚 Docs: keyb 

### ISSUE THREAD

**Issue by tim1737** [Matt-FTW/dotfiles#28]
### Did you check existing doc request?

- [X] I have searched the existing requests of the repo
- [X] I have searched the existing requests of used programs related to this request
- [X] I have read the [FAQ](https://github.com/Matt-FTW/dotfiles/blob/main/.github/FAQ.md)

### Description of the request

Another small question, maybe it will also be useful to someone, why is there a keyb in the project, what is it, through which these shortcuts are managed? because I couldn't find a package for this, I tried to delete the directory and everything remained unchanged. What is it for?

### Current Documentation

None

### Proposed Documentation

None

**Comment by Matt-FTW** [comment]
[Check the official project](https://github.com/kencx/keyb). It's basically a cheatsheet for the hotkeys of the programs in the configuration. I left it because its a time consuming thing and I don't have time to do it right now. If you wanna check what i have, use the Win + ? hotkey to bring up a rofi menu with all of the programs. Click on one and it should spawn the keyb process, if you have it installed.
