### ISSUE TITLE
Neovim Issue

### ISSUE THREAD

**Issue by S4NKALP** [Matt-FTW/dotfiles#5]
### Nvim Plugins issue 

The floatterm plugin is not working. All colorscheme also not showing in ui colorscheme  options

**Comment by Matt-FTW** [comment]
Hey,

What do you mean about the colorschemes not showing in the options? That they dont appear in the LazyVim extras?

About the floaterm issue, it should be fixed now.  Seems like there was an issue with the catppuccin theme, because LazyVim was falling back into tokyonight.  All the others themes worked correctly though.

Let me know if that helped!

**Comment by S4NKALP** [comment]
whenever i try to toggle terminal it show this error  

![Screenshot_02-Jan_21-23-44_18670](https://github.com/Matt-FTW/dotfiles/assets/98226895/73d7a921-1351-4278-bf1b-1bd953ba7d38)

**Comment by Matt-FTW** [comment]
I see, you're calling the mapping for the telescope extension of floaterm. If you did not create any terminal before is going to throw that error. What you have to do is to create a terminal before hand. To do so, you have various options. Take a look at the keys section of the floaterm plugin. For example, create a new floating terminal with <space>ftf and then call the telescope mapping to see the available floaterm teminals.

The error is problem of the telescope-floaterm extension, not mine. If you don't like you can submit an issue over there.

**Comment by S4NKALP** [comment]
thanks it work.
Will you add keybind of nvim in readme section as i am using nvim config only

**Comment by Matt-FTW** [comment]
I will, but it's gonna take some time. Once I have it I'll let you know.
